name = "AlgEffectus"
version = "0.1.0"
defaultTargets = ["algeffectus"]
moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.19.0"

[[require]]
name = "LeanCopilot"
git = "https://github.com/lean-dojo/LeanCopilot.git"
rev = "v4.19.0"

[[require]]
name = "aesop"
git  = "https://github.com/leanprover-community/aesop"
rev = "v4.19.0"

[[lean_lib]]
name = "AlgEffectus"
srcDir = "src"

[[lean_exe]]
name = "algeffectus"
root = "Main"

[[lean_exe]]
name = "tests"
root = "Tests.All"
