name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Lean
        uses: leanprover/lean-action@v1

      - name: Build project
        run: lake build

      - name: Run tests
        run: lake exe tests
